uploads = []

[[generated]]
id = "v8C6l-0X5hEvYMLbmxx1e"
uri = "file://artifacts/mockup-sandbox/public/images/novadash-dashboard-modern.png"
type = "image"
title = "SaaS dashboard mockup"

[[generated]]
id = "hN5o8Rf6auCnmphhWdGCy"
uri = "file://artifacts/mockup-sandbox/public/images/nd-bold-hero.png"
type = "image"
title = "Bold B2B SaaS Dashboard UI"

[[generated]]
id = "Fe6_u5YnwHKn6W56rO-D3"
uri = "file://artifacts/mockup-sandbox/public/images/nd-elegant-dashboard.png"
type = "image"
title = "elegant dark dashboard ui"

[[generated]]
id = "p4ZYeDOeEd3WQLBuSe917"
uri = "file://artifacts/mockup-sandbox/public/images/novadash-dashboard-grid.png"
type = "image"
title = "Swiss grid style dashboard UI"

[[generated]]
id = "wilaQ9Gv8NfgVafIOvd6Q"
uri = "file://artifacts/mockup-sandbox/public/images/novadash-console-hero.png"
type = "image"
title = "Logistics console dashboard mock"

[[generated]]
id = "82qV_pLRZllyl6olWt63J"
uri = "file://artifacts/mockup-sandbox/public/images/nd-editorial-hero.png"
type = "image"
title = "Editorial business owner packing"

[[generated]]
id = "OrmfSjKicKIZMd1rJqZ00"
uri = "file://artifacts/mockup-sandbox/public/images/nd-editorial-process.png"
type = "image"
title = "Editorial boxes and labels"

[[generated]]
id = "_wwpywSTosZifZubPkYf6"
uri = "file://artifacts/mockup-sandbox/public/images/novadash-console-hero-bright.png"
type = "image"
title = "Bright high-tech operations console dashboard"

[[outputs]]
id = "KWFzG_rXFYpaSyt41KODn"
uri = "file://paylogic-monitor.tar.gz"
type = "unspecified"
title = "paylogic-monitor.tar.gz"
