// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/novadash-bold/Home.tsx": () => import("../components/mockups/novadash-bold/Home.tsx"),
  "./components/mockups/novadash-elegant/Home.tsx": () => import("../components/mockups/novadash-elegant/Home.tsx"),
  "./components/mockups/novadash-modern/Home.tsx": () => import("../components/mockups/novadash-modern/Home.tsx")
};
